# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Careerjet
version:      0.08
version_from: lib/WebService/Careerjet.pm
installdirs:  site
requires:
    Carp:                          1.03
    Getopt::Std:                   1.05
    HTTP::Request:                 1.4
    JSON:                          2.07
    LWP::UserAgent:                2.033
    Test::More:                    0
    Text::Wrap:                    2001.09292
    URI::Escape:                   3.28

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
